const data = [
  {
    key: "1",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "2",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "3",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "4",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "5",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "6",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "7",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "8",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "9",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "10",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "11",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "12",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "13",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "14",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "15",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "16",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "17",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "18",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "19",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "20",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "21",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "22",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "23",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "24",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "25",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "26",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "27",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "28",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "29",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "30",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "31",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "32",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "33",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "34",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "35",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "36",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "37",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "38",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "39",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "40",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "41",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "42",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "43",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "44",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "45",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "46",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "47",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "48",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "49",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "50",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "51",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "52",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "53",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "54",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "55",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "56",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "57",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "58",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "59",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "60",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "61",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "62",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "63",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "64",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "65",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "66",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "67",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "68",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "69",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "70",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "71",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "72",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "73",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "74",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "75",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "76",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "77",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "78",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "79",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "80",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "81",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "82",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "83",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "84",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "85",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "86",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "87",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "88",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "89",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "90",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "91",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "92",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "93",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "94",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "95",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "96",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "97",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "98",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "99",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "100",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "101",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "102",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "103",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "104",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "105",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "106",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "107",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "108",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "109",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "110",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "111",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "112",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "113",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "114",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "115",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "116",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "117",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "118",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "119",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "120",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "121",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "122",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "123",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "124",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "125",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "126",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "127",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "128",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "129",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "130",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "131",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "132",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "133",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "134",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "135",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "136",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "137",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "138",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "139",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "140",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "141",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "142",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "143",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "144",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "145",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "146",
    name: "QA Engineer Needed",
    status: "Open",
    publishedDate: "2024-05-17",
    closingDate: "2024-05-20",
    organization: "Instagram",
    organizationLogo:
      "https://w7.pngwing.com/pngs/999/686/png-transparent-duluth-logo-business-instagram-logo-text-photography-magenta-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: false,
  },
  {
    key: "147",
    name: "Food Tester Full-time",
    status: "Closed",
    publishedDate: "2024-05-03",
    closingDate: "2024-05-05",
    organization: "Unilever",
    organizationLogo:
      "https://w7.pngwing.com/pngs/592/653/png-transparent-logo-unilever-business-business-blue-text-people-thumbnail.png",
    classification: "Food Industry",
    featured: true,
  },
  {
    key: "148",
    name: "Article Reviewer for Twitter",
    status: "Cancelled",
    publishedDate: "2023-07-14",
    closingDate: "2023-07-17",
    organization: "Twitter",
    organizationLogo:
      "https://w7.pngwing.com/pngs/822/1023/png-transparent-logo-computer-icons-business-twitter-miscellaneous-leaf-company-thumbnail.png",
    classification: "Computers, Telecommunications ICT Equipment",
    featured: true,
  },
  {
    key: "149",
    name: "Pilot needed with 5+ years of Experience",
    status: "Archived",
    publishedDate: "2024-02-10",
    closingDate: "2024-02-25",
    organization: "Boeing",
    organizationLogo:
      "https://w7.pngwing.com/pngs/753/623/png-transparent-logo-boeing-business-boeing-logo-blue-text-logo-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
  {
    key: "150",
    name: "Driver required with 2 yrs of exp.",
    status: "Awarded",
    publishedDate: "2023-12-17",
    closingDate: "2023-12-24",
    organization: "24/7 Transpo",
    organizationLogo:
      "https://w7.pngwing.com/pngs/949/554/png-transparent-business-logo-logistics-transport-business-blue-hat-text-thumbnail.png",
    classification: "Automotive/Industrial",
    featured: true,
  },
];

export default data;
